from __future__ import annotations

import subprocess
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent.parent
LOCAL_ENV_PATH = PROJECT_DIR / "local-supabase.env"
LOCAL_AUTH_EMAIL = "local@shelfpath.test"
LOCAL_AUTH_PASSWORD = "local-shelfpath-password"


def main() -> None:
    status = subprocess.run(
        ["supabase", "status", "-o", "env"],
        cwd=PROJECT_DIR,
        check=True,
        text=True,
        capture_output=True,
    )
    values = _parse_env(status.stdout)
    api_url = _required(values, "API_URL")
    anon_key = _required(values, "ANON_KEY")
    service_role_key = _required(values, "SERVICE_ROLE_KEY")
    LOCAL_ENV_PATH.write_text(
        "\n".join(
            [
                "# Generated by scripts/write_local_supabase_env.py.",
                "# Local-only Supabase sandbox; do not point this file at production.",
                "SHELFPATH_STORAGE=supabase",
                "SHELFPATH_DEBUG=true",
                "SHELFPATH_SESSION_SECRET=local-development-change-me",
                f"SUPABASE_URL={api_url}",
                f"SUPABASE_PUBLISHABLE_KEY={anon_key}",
                f"SUPABASE_SERVICE_ROLE_KEY={service_role_key}",
                f"SHELFPATH_LOCAL_AUTH_EMAIL={LOCAL_AUTH_EMAIL}",
                f"SHELFPATH_LOCAL_AUTH_PASSWORD={LOCAL_AUTH_PASSWORD}",
                "OPENAI_MODEL=gpt-4.1-mini",
                "",
            ]
        ),
        encoding="utf-8",
    )
    print(f"Wrote {LOCAL_ENV_PATH.relative_to(PROJECT_DIR)} for local Supabase testing.")


def _parse_env(output: str) -> dict[str, str]:
    values = {}
    for line in output.splitlines():
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", maxsplit=1)
        values[key.strip()] = value.strip().strip('"')
    return values


def _required(values: dict[str, str], key: str) -> str:
    value = values.get(key)
    if not value:
        raise RuntimeError(f"supabase status -o env did not include {key}.")
    return value


if __name__ == "__main__":
    main()
